### ISSUE TITLE
Customised Rulebook with POJO rules

### ISSUE THREAD

**Issue by jabhijeet** [rulebook-rules/rulebook-rules.github.io#1]
This is a great simple application. Thank you for the project. I have a question regarding creation of a customised rule book. Currently, the way a rule book is initialised for POJO rules is by specifying the package. But how can i group the rules and customise the rule book for that group.? With this approach, I can define the rules anywhere but execute the rules in a specific group.

**Comment by Clayton7510** [comment]
Wow, I just noticed this since it was published under issues in the github.io website. And I don't watch issues on this repo. Sorry about that. In the future, if you have a question, post in under the rulebook repo for a faster response.

BTW, if you're still a RuleBook user, thanks for the support.

I know this is an old question, but I'll provide a response, anyway.

POJO rules are based on Package. But that is only if you are using a RuleBookRunner. You can setup your own POJO RuleBooks any way you like. You can just create a RuleBook and add your POJO Rules by using the com.deliveredtechnologies.rulebook.model.runner.RuleAdapter class. RuleAdapter accepts a POJO rule as an argument in the constructor and "adapts" the POJO rule to a Rule class, usable in a RuleBook.

**Comment by jabhijeet** [comment]
Thank you
